[package]
name = "ultra96v2_udmabuf_sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#jelly-mem_access = "0.2.3"
jelly-mem_access = { path = "../../../../../rust/mem_access" }
