[package]
name = "zynqmp_armv7r"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"

[build-dependencies]
cc = "1.0.36"
